
spring:
  application:
    name: identity-service

server:
  port: 8093

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka
  instance:
    preferIpAddress: true
    hostName: 192.168.43.77

keycloak:
  realm: PRS
  ssl-required: external
  use-resource-role-mappings: true
  bearer-only: true
  resource: backend
  auth-server-url: http://localhost:8090
